version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
      - ./grafana/config:/etc/grafana:rw
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  influxdb:
      image: influxdb:2.7.1
      ports:
      - "8086:8086"
      volumes:
      - ./influxdb2:/var/lib/influxdb
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: cloudquerydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - '5432:5432'
    volumes:
      - ~/postgresql/data:/var/lib/postgresql/data
