serviceName: 'game-server-base-dev'
containers:
  game-server:
    image: ':game-server-populate-env-variables-correctly-CHAIN_HERE.game-server.latest'
    environment:
      MUMBAI_POLYGON_RPC_URL: ''
      POLYGON_PAYMENT_CONTRACT: ''
      TOWER_TOKEN_POLYGON_SCORE: ''
      TOWER_PAYMENT_SCORE: ''
      SIMULATION_CORE_SCORE: ''
      SIMULATION_PARTICIPATION_SCORE: ''
      SIMULATION_ASSET_MANAGER_SCORE: ''
      GBET_STAKING_SCORE: ''
      TOWER_STAKING_SCORE: ''
      SIMULATION_SCORE: ''
      LOOTBOX_SCORE: ''
      GANGSTABET_SCORE_PROD: ''
      TOWER_CARD_POLYGON_SCORE: ''
      BASE_RENTAL_SCORE: ''
      TOWER_ERC20_SCORE: ''
      SNEAKMOVE_SCORE: ''
      ITEM_SCORE: ''
      WEAPON_SCORE: ''
      GANGWAR_PUBLISHER_SCORE: ''
      LOOTBOX_CLAIM_SCORE: ''
      AGENDA_STATUS: ''
      REGEN_PAYMENT_BASE_TREASURY_ADDRESS: ''
      REGEN_PAYMENT_ICON_CROWN_PAYMENT_AMOUNT: ''
      REGEN_PAYMENT_ICON_TREASURY_ADDRESS: 'hx9e92e15d85b83de420f7becd4484b4b8f4beb664'
      AES_KEY: ''
      TREASURY_ADDRESS_BASE: ''
      GBET_STAKING_STATUS: ''
      TOWER_STAKING_STATUS: ''
      BASE_SCAN_ENDPOINT_URL: ''
      BASE_SCAN_API_KEY: ''
      PORT: '3000'
      CHAIN: 'base'
      BRIDGE_STATUS: ''
      CHARACTER_GEN_BASE_STATUS: ''
      BASE_NETWORK: ''
      BRIDGE_NETWORK: ''
      BASE_URL: ''
      MONGO_URI: ''
      TOWER_EXTERNAL_API: ''
      CLIENT_ID_THIRDWEB: ''
      SECRET_KEY_THIRDWEB: ''
      PRIVATE_KEY_THIRDWEB: ''
      WEBSOCKET_ICON: ''
      LOOTCRATE_ICON: ''
      LOOTCRATE_BRIDGE_BASE: ''
      LOG_FORMAT: ''
      ORIGIN: '*'
      CREDENTIALS: 'true'
      ENVIRONMENT: 'base-dev'
      LOCAL_RUN: 'disable'
      NETWORK_URL: ''
      NID: ''
      CLOUDWATCH_GROUP_NAME: 'game-server'
      CLOUDWATCH_LOG_STREAM: ''
      CLOUDWATCH_ACCESS_KEY: ''
      CLOUDWATCH_SECRET_ACCESS_KEY: ''
      CLOUDWATCH_REGION: 'ap-southeast-2'
      USDC_SCORE: ''
      PRIVATE_KEY: '020712532a90575e5e8d56a2a587acf7196a3feaae7b76c7ee254e824b7a41bf'
      TREASURY_ADDRESS: 'hx52a5f71f8f6323adf618362e647f645e786b9b9d'
      PRIVATE_KEY_FIREBASE: ''
      TYPE: ''
      AWS_ASSET_BUCKET_URL: 'https://gangwar-bucket-prod.s3.ap-southeast-2.amazonaws.com'
      JWT_SECRET: ''
      WS_SECRET: ''
      PROJECT_ID: ''
      PRIVATE_KEY_ID: ''
      CLIENT_EMAIL: ''
      CLIENT_ID: ''
      AUTH_URI: ''
      TOKEN_URI: ''
      AUTH_PROVIDER_X509_CERT_URL: ''
      CLIENT_x509_CERT_URL: ''
      DISCORD_ALERT: 'on'
      DISCORD_WEBHOOK: ''
      GBET_EXTERNAL_API: ''
      CHARACTER_METADATA_S3_LINK: 'https://d2fmrm28yajfa.cloudfront.net/metadata'
      POLYGON_NETWORK: ''
      ARWEAVE_KEY: ''
      BOT_ADDRESS_WHITELIST_TOKEN: ''
      BOT_WHITELIST_CLIENT_ID: ''
      BOT_WHITELIST_ROLE_ID: ''
      DISCORD_BOT_ACCESS_TOKEN_REQ: ''
      FREEMINT_SCORE: ''
      ACCOUNT1: ''
      ACCOUNT2: ''
      ACCOUNT3: ''
      ACCOUNT4: ''
      ACCOUNT5: ''
      PK1: ''
      PK2: ''
      PK3: ''
      PK4: ''
      PK5: ''
      FARCASTER_SECRET: ''
      FARCASTER_MINT_SCORE: ''
    ports:
      '3000': 'HTTP'
publicEndpoint:
  containerName: 'game-server'
  containerPort: 3000
  healthCheck:
    healthyThreshold: 2
    unhealthyThreshold: 3
    timeoutSeconds: 25
    intervalSeconds: 45
    path: '/'
    successCodes: '200'