name: Bump version - pre-release
on:
  push:
    branches:
      - main
      - test-ci
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          pre_release_branches: test-ci
          default_prerelease_bump: true
          append_to_pre_release_tag: alpha
          tag_prefix: v
